name: FriendPlugin
version: '${project.version}'
main: me.asuks.friendplugin.FriendPlugin

commands:
  friend:
    aliases: f
  friend-list:
    aliases: fl
  AddFriend:
  SaveFile:
    aliass: svf
  ReadJson:
    aliass: rjs
